### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: clojure/core$pr_str on JDK11

### ISSUE THREAD

**Issue by hamann** [pyr/signal#3]
I'm getting an exception with a basic signal handler like
```clojure
(defn add-signal-handler [signal]
  (signal-handler/with-handler signal
    (log/info ::system-signal-handler {:signal signal})))
```

```
2020-02-28 09:39:47.924 ERROR com.nextjournal.exception-handler - {:msg "Uncaught exception on SIGTERM handler", :line 71}
java.lang.ExceptionInInitializerError: null
 at com.nextjournal.journal$add_signal_handler$fn__69757.invoke(journal.clj:107)
 at signal.handler$__GT_handler$fn__69686.invoke(handler.clj:23)
 at signal.handler.proxy$java.lang.Object$SignalHandler$d8c00ec7.handle(Unknown Source)
 at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
 at java.base/jdk.internal.misc.Signal$1.run(Signal.java:220)
 at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: clojure/core$pr_str
 at java.base/java.lang.Class.forName0(Native Method)
 at java.base/java.lang.Class.forName(Class.java:398)
 at clojure.lang.RT.classForName(RT.java:2211)
 at clojure.lang.RT.classForName(RT.java:2220)
 at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1317)
 at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:853)
 at clojure.lang.LispReader.read(LispReader.java:285)
 at clojure.lang.LispReader.read(LispReader.java:216)
 at clojure.lang.LispReader.read(LispReader.java:205)
 at clojure.lang.RT.readString(RT.java:1878)
 at clojure.lang.RT.readString(RT.java:1873)
 at com.nextjournal.journal$add_signal_handler$fn__69757$fn__69760.<clinit>(journal.clj:107)
 ... 6 common frames omitted
```

```sh
$ java -version
Picked up _JAVA_OPTIONS: -XX:+UseG1GC
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
```

Do you have any idea what's going on here?

**Comment by pyr** [comment]
I think I will need more context, I am unable with the same JVM version to get to the same result, I'm also surprised to see the `pr-str` mention. Can I ask that you create a full minimal reproduction of the issue that I can work from?

**Comment by hamann** [comment]
@pyr we ran into a similar issue like https://github.com/riemann/riemann/pull/951. Setting the classloader on the signal handling thread fixed it.

**Comment by KingMob** [comment]
@pyr Would you consider reopening this? We ran into a variant of the same issue with Aleph.

It's not very well-documented that the context class loader for signal handlers is null, aka the bootstrap loader, which can't load most Java classes or Clojure code. Our fix was the same as Riemann's, to manually set it to clojure's Compiler class loader, DynamicClassLoader, which includes the app and extension loaders in its chain. We lost a lot of time on this.

If you need a reproducible test case, check out https://github.com/ivarref/aleph-shutdown-stacktrace

**Comment by KingMob** [comment]
Great! Lmk if you want a PR.

**Comment by pyr** [comment]
Thanks for the reproduction case, #4 should address the issue.

**Comment by pyr** [comment]
Thanks for the reproduction case, I can confirm that #4 fixes it for your reproduction repo (once switched to signal instead of a hand-rolled handler)

**Comment by danielcompton** [comment]
@pyr would you be able to cut a new release with this fix in it?

**Comment by pyr** [comment]
@danielcompton done

**Comment by danielcompton** [comment]
Thank you!
